spring:
    application:
        name: urlshortner
    jackson.default-property-inclusion: NON_NULL
    datasource:
        # you can try persist data to a file with H2 db.
        #url: jdbc:h2:file:/Users/deepak.chaudhary/Documents/CrederaProjects/data10
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                '[format_sql]': true
        show-sql: true
    h2:
        console:
            enabled: true

logging:
    level:
        root: INFO
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor.sql.BasicBinder: TRACE
            # aspectj: TRACE
            # springframework: TRACE